name: Auto Build and Push n8n for Render

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js with Corepack
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          cache: 'pnpm'

      - name: Enable Corepack and install PNPM
        run: |
          corepack enable
          corepack prepare pnpm@8 --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build
